// <auto-generated />
using System;
using Angel_Morel_P2_AP1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Angel_Morel_P2_AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250318002356_encuestas")]
    partial class encuestas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Angel_Morel_P2_AP1.Model.Ciudades", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadId"));

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CiudadId");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            CiudadId = 1,
                            Monto = 0,
                            Nombre = "Nagua"
                        },
                        new
                        {
                            CiudadId = 2,
                            Monto = 0,
                            Nombre = "Samana"
                        },
                        new
                        {
                            CiudadId = 3,
                            Monto = 0,
                            Nombre = "Rio San Juan"
                        });
                });

            modelBuilder.Entity("Angel_Morel_P2_AP1.Model.Encuestas", b =>
                {
                    b.Property<int>("EncuestasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncuestasId"));

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("EncuestasId");

                    b.ToTable("Encuestas");
                });

            modelBuilder.Entity("Angel_Morel_P2_AP1.Models.EncuestaDestalles", b =>
                {
                    b.Property<int>("DetallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetallesId"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.HasKey("DetallesId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EncuestaId");

                    b.ToTable("Destalles");
                });

            modelBuilder.Entity("Angel_Morel_P2_AP1.Models.EncuestaDestalles", b =>
                {
                    b.HasOne("Angel_Morel_P2_AP1.Model.Ciudades", "Ciudades")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Angel_Morel_P2_AP1.Model.Encuestas", "Encuestas")
                        .WithMany("EncuestaDetalles")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudades");

                    b.Navigation("Encuestas");
                });

            modelBuilder.Entity("Angel_Morel_P2_AP1.Model.Encuestas", b =>
                {
                    b.Navigation("EncuestaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
